# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-30 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user_id', models.IntegerField()),
                ('follower_user_id', models.IntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
